export const defaultWords = [
  { en: "attractive", cz: "atraktivní, přitažlivý", category: "Fyzický vzhled" },
  { en: "bald", cz: "plešatý", category: "Fyzický vzhled" },
  { en: "blonde", cz: "blond (světlovlasý)", category: "Fyzický vzhled" },
  { en: "curly", cz: "kudrnatý", category: "Fyzický vzhled" },
  { en: "cute", cz: "roztomilý", category: "Fyzický vzhled" },
  { en: "dark", cz: "tmavý (vlasy/pleť)", category: "Fyzický vzhled" },
  { en: "fair", cz: "světlý (vlasy/pleť)", category: "Fyzický vzhled" },
  { en: "good-looking", cz: "pohledný, hezký", category: "Fyzický vzhled" },
  { en: "gorgeous", cz: "nádherný, úchvatný", category: "Fyzický vzhled" },
  { en: "long", cz: "dlouhý", category: "Fyzický vzhled" },
  { en: "medium-height", cz: "středně vysoký", category: "Fyzický vzhled" },
  { en: "medium-length", cz: "středně dlouhý", category: "Fyzický vzhled" },
  { en: "plain", cz: "obyčejný, nevýrazný", category: "Fyzický vzhled" },
  { en: "pretty", cz: "pěkná, hezká", category: "Fyzický vzhled" },
  { en: "short", cz: "malý / krátký", category: "Fyzický vzhled" },
  { en: "spiky", cz: "ježatý (účes)", category: "Fyzický vzhled" },
  { en: "stocky", cz: "podsaditý, zavalitý", category: "Fyzický vzhled" },
  { en: "straight", cz: "rovný (vlasy)", category: "Fyzický vzhled" },
  { en: "strong", cz: "silný", category: "Fyzický vzhled" },
  { en: "tall", cz: "vysoký", category: "Fyzický vzhled" },
  { en: "thin", cz: "hubený, štíhlý", category: "Fyzický vzhled" },
  { en: "wavy", cz: "vlnitý", category: "Fyzický vzhled" },
  { en: "well-built", cz: "dobře stavěný", category: "Fyzický vzhled" },
  { en: "affectionate", cz: "srdečný, přátelský", category: "Osobnost" },
  { en: "arrogant", cz: "arogantní, namyšlený", category: "Osobnost" },
  { en: "artistic", cz: "umělecky založený", category: "Osobnost" },
  { en: "bossy", cz: "rozkazovačný", category: "Osobnost" },
  { en: "cheerful", cz: "veselý, radostný", category: "Osobnost" },
  { en: "clever", cz: "chytrý, bystrý", category: "Osobnost" },
  { en: "confident", cz: "sebevědomý", category: "Osobnost" },
  { en: "determined", cz: "odhodlaný", category: "Osobnost" },
  { en: "easy-going", cz: "pohodový, klidný", category: "Osobnost" },
  { en: "energetic", cz: "energický", category: "Osobnost" },
  { en: "generous", cz: "štědrý, velkorysý", category: "Osobnost" },
  { en: "hard-working", cz: "pracovitý", category: "Osobnost" },
  { en: "impatient", cz: "netrpělivý", category: "Osobnost" },
  { en: "likeable", cz: "sympatický", category: "Osobnost" },
  { en: "lively", cz: "živý, čilý", category: "Osobnost" },
  { en: "loyal", cz: "loajální, věrný", category: "Osobnost" },
  { en: "optimistic", cz: "optimistický", category: "Osobnost" },
  { en: "outgoing", cz: "společenský, otevřený", category: "Osobnost" },
  { en: "patient", cz: "trpělivý", category: "Osobnost" },
  { en: "reliable", cz: "spolehlivý", category: "Osobnost" },
  { en: "sensible", cz: "rozumný", category: "Osobnost" },
  { en: "sensitive", cz: "citlivý", category: "Osobnost" },
  { en: "serious", cz: "vážný", category: "Osobnost" },
  { en: "shy", cz: "plachý, stydlivý", category: "Osobnost" },
  { en: "talkative", cz: "povídavý, ukecaný", category: "Osobnost" },
  { en: "tidy", cz: "pořádný, čistotný", category: "Osobnost" },
  { en: "well-organised", cz: "dobře zorganizovaný", category: "Osobnost" },
] as const;
